# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.16.0
    working_directory: ~/rbac

    steps:
      - checkout

      # Cache dependencies
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "yarn.lock" }}
            - v2-deps-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v2-deps-{{ checksum "yarn.lock" }}

      # Build and test
      - run:
          name: Build Project
          command: yarn build

      - run:
          name: Run Tests
          command: yarn test

      # Cache build artifacts
      - save_cache:
          paths:
            - lib
            - dist
          key: v2-build-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}

  test-npm:
    docker:
      - image: cimg/node:20.16.0
    working_directory: ~/rbac

    steps:
      - checkout

      # Restore build cache
      - restore_cache:
          keys:
            - v2-build-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "package.json" }}

      # Install database adapters in main project
      - run:
          name: Install Database Adapters
          command: |
            yarn add mongodb mysql2 pg
            yarn list mongodb mysql2 pg # Verify dependencies are installed

      # Install test dependencies
      - run:
          name: Install Test Dependencies
          command: |
            cd test/npm-test
            npm install
            npm ls mongodb # Verify MongoDB is installed

      # Run npm test
      - run:
          name: Test npm Package
          command: yarn test:npm

workflows:

  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - develop
                - /feature\/.*/
                - /hotfix\/.*/
                - /release\/.*/
      - test-npm:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - develop
                - /feature\/.*/
                - /hotfix\/.*/
                - /release\/.*

  pull-request:
    jobs:
      - build
      - test-npm:
          requires:
            - build
